package net.justgnat.mcfdoc.printer;

import net.justgnat.mcfdoc.Logger;
import net.justgnat.mcfdoc.Options;
import net.justgnat.mcfdoc.parser.*;
import net.justgnat.mcfdoc.sanitiser.HtmlSanitiser;
import static net.justgnat.mcfdoc.printer.HtmlUtil.*;

import java.io.File;
import java.io.FileWriter;
import java.util.Collection;
import java.util.List;

public class DatapackPrinter {

    public static final String STYLES = """
            <style> h5 { line-height: 0.2px; font-size: 15px; } h2, h1 { font-style: italic; } h2 { font-style: italic; } h4 { background-color: #DEE3E9; font-family: "Lucida Console", "Courier New"; padding: 8px; } h5 { font-family: Verdana, sans-serif; } .methodname { font-family: "Lucida Console", "Courier New", monospace; } .block { border: 1px solid #f0f0f0ff; padding: 8px; margin: 15px; background-color: #f8f8f8ff; } .tabletitle { font-style: bold, italic; font-family: arial, sans-serif; font-size: 20px; color: #323232; } .methodheader { font-family: "Lucida Console", "Courier New", monospace; background-color: #DEE3E9; } table { font-family: arial, sans-serif; border-collapse: collapse; border: 0px solid #ddddddff; width: 100%; background-color: #FFFFFF; } td, th { text-align: left; padding: 8px; } th { background-color: #DDDDDD; } tr:nth-child(odd) { background-color: #dddddd66; } a { color: inherit; text-decoration: none; } a:hover { color: #991100; }</style>""";

    private final Datapack datapack;

    private final TypeManager typeManager;

    private final Options options;

    public DatapackPrinter(Datapack datapack, Options options, TypeManager typeManager) {
        this.datapack = datapack;
        this.typeManager = typeManager;
        this.options = options;
    }

    /**
     * Attempts to print the given Datapack. Does not indicate whether it succeeds or not.
     */
    public static void printDatapack(Datapack datapack, Options options, TypeManager typeManager) {
        DatapackPrinter printer = new DatapackPrinter(datapack, options, typeManager);
        printer.print();
    }

    private void print() {
        if (!checkPath(options.outputPath, options.canOverwrite))
            return;

        try (FileWriter writer = new FileWriter(options.outputPath)) {
            writer.write(generateHtml());
            Logger.write("Wrote to " + options.outputPath);
        } catch (Exception e) {
            Logger.write("Failed Print: " + e);
        }
    }

    private boolean checkPath(String path, boolean canOverwrite) {
        File file = new File(path);
        if (!file.exists())
            return true;

        if (!canOverwrite) {
            if (!file.isDirectory()) {
                Logger.write("File already exists! Use the flag [overwrite=<true|false>] to specify whether overwriting is permitted");
            } else {
                Logger.write("Can not overwrite a directory");
            }
            return false;
        }
        return true;
    }

    private String generateHtml() {
        String header =
                "<!DOCTYPE html>" +
                        "<html>" +
                        "<head>" +
                        "<title>" + datapack.name() + "</title>" +
                        STYLES +
                        "</head>" +
                        "<body>";

        String credits = "Automatically generated by " + "<a href=\"https://github.com/ThisIsMyName314/MCFDoc_Information\" style=\"all:revert\">MCFDoc</a>" +
                " at " + System.currentTimeMillis();

        String footer = h5(credits) + "</body></html>";

        String title = h1(datapack.name());
        String subtitle = (datapack.hasVersion() ? datapack.version() : "");
        if (datapack.hasAuthors()) subtitle += " by " + datapack.author();

        return header +
                title + // Do not need to sanitise as these are provided at the command line
                h2(subtitle) +
                p(datapack.description()) +
                generateTypeBlock() +
                generateFunctionSummary() +
                generateFunctionDetail() +
                footer;
    }

    private String generateTypeBlock() {
        if (typeManager.getCustomTypes().isEmpty())
            return "";

        return div("block",
                h2("tabletitle", "Declared Types") +
                        table(
                            tr(th("Name") + th("Description")) +
                               generateTypeRows()
                        )
        );
    }

    private String generateTypeRows() {
        StringBuilder sb = new StringBuilder();
        for (CustomType type : typeManager.getCustomTypes()) {
            sb.append("<tr>")
                    .append(td(sanitise(type.name())))
                    .append(td(sanitise(type.description())))
                    .append("</tr>");
        }
        return sb.toString();
    }

    private String generateFunctionSummary() {
        if (datapack.groups().isEmpty())
            return "";

        return div("block",
                h2("tabletitle", "Function Summary") +
                        table(
                            tr(th("Name") + th("Description")) +
                                    generateFunctionSummaryRows()
                        )
        );
    }

    private String generateFunctionSummaryRows() {
        StringBuilder sb = new StringBuilder();
        for (FunctionGroup module : datapack.groups()) {
            for (Function function : module.functions()) {
                if (function.isHidden() && !options.showHidden)
                    continue;
                sb.append("<tr>");
                sb.append(td(a("#" + function.name(), function.name() + (function.isDeprecated() ? " (deprecated)" : ""))));
                sb.append(td(sanitise(
                        getSingleLineDescription(function.description())
                )));
                sb.append("</tr>");
            }
        }
        return sb.toString();
    }

    private String getSingleLineDescription(String string) {
        int lineBreak = string.indexOf("<br>");
        if (lineBreak == -1) {
            if (string.length() < 100)
                return string;
            return string.substring(0, 97) + "...";
        }
        return string.substring(0, lineBreak);
    }

    private String generateFunctionDetail() {
        if (datapack.groups().isEmpty())
            return "";

        return div("block",
                h2("tabletitle", "Function Detail") +
                        table(
                                generateFunctionDetailRows()
                        )
        );
    }

    private String generateFunctionDetailRows() {
        StringBuilder sb = new StringBuilder();

        for (FunctionGroup group : datapack.groups()) {
            for (Function function : group.functions()) {
                if (function.isHidden() && !options.showHidden)
                    continue;

                sb.append("<tr> <th class=\"methodheader\" id=\"")
                        .append(function.name())
                        .append("\">")
                        .append(function.simpleName())
                        .append("</th> </tr>");
                sb.append("<tr> <td> <p class=\"methodname\"> ")
                        .append(generateFunctionString(function)).append("</p>");
                sb.append(sanitise(function.description()));
                sb.append(generateParameterBlock(function));
                sb.append(generateTagBlock(function));
            }
        }

        return sb.toString();
    }

    private String sanitise(String content) {
        return HtmlSanitiser.sanitise(content, options.html);
    }

    private String generateTagBlock(Function function) {
        Collection<List<Annotation>> tagTypes = function.annotations().getAnnotations();
        if (tagTypes.isEmpty())
            return "";

        StringBuilder sb = new StringBuilder();
        for (List<Annotation> annotationList : tagTypes) {
            /* Tag title */
            sb.append(h5(sanitise(annotationList.getFirst().getName())));
            /* Tag body */
            for (Annotation annotation : annotationList) {
                if (annotation.getBody().isEmpty()) {
                    sb.append(p("----")); // Add a gap to make it format more nicely
                } else {
                    sb.append(p(sanitise(annotation.getBody())));
                }
            }
        }
        return sb.toString();
    }

    private String generateParameterBlock(Function function) {
        if (function.parameters().isEmpty())
            return "";

        String title = h5("Parameters");
        StringBuilder sb = new StringBuilder("<p>");
        for (Parameter param : function.parameters()) {
            sb.append(sanitise(param.name()));
            if (!param.info().isEmpty()) {
                sb.append(" - ").append(sanitise(param.info()));
            }
            sb.append("<br>");
        }
        sb.append("</p>");
        return title + sb;
    }

    private String generateFunctionString(Function function) {
        StringBuilder sb = new StringBuilder(function.name() + "(");
        int i = 0;
        for (Parameter param : function.parameters()) {
            ++i;
            if (options.prefixTypesInOutput) {
                sb.append(param.type().getColouredName()).append(" ").append(sanitise(param.name()));
            } else {
                sb.append(sanitise(param.name())).append(": ").append(param.type().getColouredName());
            }
            if (i != function.parameters().size()) {
                sb.append(", ");
            }
        }
        sb.append(")");
        return sb.toString();
    }

}
