package net.justgnat.mcfdoc.printer;

import net.justgnat.mcfdoc.Logger;
import net.justgnat.mcfdoc.Options;
import net.justgnat.mcfdoc.parser.*;
import net.justgnat.mcfdoc.sanitiser.HtmlSanitiser;
import static net.justgnat.mcfdoc.printer.HtmlUtil.*;

import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.List;

public class DatapackPrinter {

    public static final String STYLES =
        """
        <style> h5 {line-height: 0.2px;}
        h2, h1 {font-style: italic;}
        h3 {background-color: #4D7A97AA;}
        h4 {background-color: #DEE3E9; font-family: "Lucida Console", "Courier New"; padding: 8px;}
        h5 {font-family: Verdana, sans-serif;}
        body {background-color: #F1F1F1;}
        .code {font-family: "Lucida Console", "Courier New", monospace;}
        .func_block {background-color: #FFFFFF;} </style>
        """;

    private final Datapack datapack;

    private final TypeManager typeManager;

    private final Options options;

    public DatapackPrinter(Datapack datapack, Options options, TypeManager typeManager) {
        this.datapack = datapack;
        this.typeManager = typeManager;
        this.options = options;
    }

    /**
     * Attempts to print the given Datapack. Does not indicate whether it succeeds or not.
     */
    public static void printDatapack(Datapack datapack, Options options, TypeManager typeManager) {
        DatapackPrinter printer = new DatapackPrinter(datapack, options, typeManager);
        printer.print();
    }

    private void print() {
        if (!checkPath(options.outputPath, options.canOverwrite))
            return;

        try (FileWriter writer = new FileWriter(options.outputPath)) {
            writer.write(generateHtml());
            Logger.write("Wrote to " + options.outputPath);
        } catch (Exception e) {
            Logger.write("Failed Print: " + e);
        }
    }

    private boolean checkPath(String path, boolean canOverwrite) {
        File file = new File(path);
        if (!file.exists())
            return true;

        if (!canOverwrite) {
            if (!file.isDirectory()) {
                Logger.write("File already exists! Use the flag [overwrite=<true|false>] to specify whether overwriting is permitted");
            } else {
                Logger.write("Can not overwrite a directory");
            }
            return false;
        }
        return true;
    }

    private String generateHtml() {
        String header =
            "<!DOCTYPE html>" +
            "<html>" +
            "<head>" +
                "<title>" + datapack.name() + "</title>" +
                STYLES +
            "</head>" +
            "<body>";

        String footer =
            h5("Automatically generated by MCFDoc on " + currentDate()) +
            "</body></html>";

        return header + generateInfo() +  generateBody() + footer;
    }

    private String generateBody() {
        StringBuilder body = new StringBuilder();

        for (FunctionGroup group : datapack.groups()) {
            // body.append(h3("Module " + group.namespace()));
            for (Function f : group.functions()) {
                if (!f.isHidden() || options.showHidden) {
                    body.append(generateFunctionBodyHtml(f));
                }
            }
        }
        return body.toString();
    }

    private String currentDate() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yy");
        return df.format(new Date());
    }

    private String sanitise(String content) {
        return new HtmlSanitiser(content, options.html).sanitise();
    }

    /*
    Generates a header listing some information (name, description, author) about the Datapack
     */
    private String generateInfo() {
        StringBuilder sb = new StringBuilder(h1(sanitise(datapack.name())));
        if (datapack.hasDescription()) {
            sb.append(h3("Description"))
              .append(p(sanitise(datapack.description())));
        }
        if (datapack.hasCredits()) {
            sb.append(h3("Credits"))
              .append(p(sanitise(datapack.author())));
        }
        if (datapack.hasVersion()) {
            sb.append(h3("Version"))
                .append(p(sanitise(datapack.version())));
        }
        if (!typeManager.getCustomTypes().isEmpty()) {
            sb.append(h2("Type summary"));
            for (CustomType type : typeManager.getCustomTypes()) {
                sb.append(generateTypeBodyHtml(type));
            }
        }
        int modules = datapack.groups().size();
        sb.append(h2("Function summary [" + modules + " Module" + (modules > 1 ? "s": "") + "]"));
        return sb.toString();
    }

    private String generateTypeBodyHtml(CustomType type) {
        return div("func_block", h4(sanitise(type.name())) +
                div("code",
                        p(sanitise(type.description()))
                )
        );
    }

    private String generateFunctionName(Function function) {
        String name = function.name(); // Do not need to sanitise as only valid MCFunction names are parsed
        if (function.isDeprecated())
            name += colour("BB1111", " (Deprecated) ");
        if (function.isHidden())
            name += colour("1111BB", " (Hidden)");
        return h4(name);
    }

    /*
    Creates the div containing all the information about the Function given
     */
    private String generateFunctionBodyHtml(Function function) {
        return div("func_block", generateFunctionName(function) +
                   div("code",
                        p(generateFunctionString(function))) +
                   p(sanitise(function.description())) +
                   generateParameterBlock(function) +
                   generateTagBlock(function)
        );
    }

    /*
    Generates a block of text listing all the
     */
    private String generateTagBlock(Function function) {
        Collection<List<Tag>> tagTypes = function.tags().getTags();
        if (tagTypes.isEmpty())
            return "";

        StringBuilder sb = new StringBuilder();
        for (List<Tag> tagList : tagTypes) {
            /* Tag title */
            sb.append(h5(sanitise(tagList.getFirst().getName())));
            /* Tag body */
            for (Tag tag : tagList) {
                if (tag.getBody().isEmpty()) {
                    sb.append(p("—")); // Add a gap to make it format more nicely
                } else {
                    sb.append(p(sanitise(tag.getBody())));
                }
            }
        }
        return sb.toString();
    }

    private String generateParameterBlock(Function function) {
        if (function.parameters().isEmpty())
            return "";

        String title = h5("Parameters");
        StringBuilder sb = new StringBuilder("<p>");
        for (Parameter param : function.parameters()) {
            sb.append(sanitise(param.name()));
            if (!param.info().isEmpty()) {
                sb.append(" - ").append(sanitise(param.info()));
            }
            sb.append("<br>");
        }
        sb.append("</p>");
        return title + sb;
    }

    private String generateFunctionString(Function function) {
        StringBuilder sb = new StringBuilder(sanitise(function.name()) + "(");
        int i = 0;
        for (Parameter param : function.parameters()) {
            ++i;
            if (options.prefixTypesInOutput) {
                sb.append(param.type().getColouredName()).append(" ").append(sanitise(param.name()));
            } else {
                sb.append(sanitise(param.name())).append(": ").append(param.type().getColouredName());
            }
            if (i != function.parameters().size()) {
                sb.append(", ");
            }
        }
        sb.append(")");
        return sb.toString();
    }

}
