package net.justgnat.mcfdoc.parser;

import net.justgnat.mcfdoc.Logger;
import net.justgnat.mcfdoc.Options;
import net.justgnat.mcfdoc.sanitiser.HtmlSanitiser;

import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.List;

public class Printer {

    public static final String STYLE_BLOCK =
            "<style> h5 {line-height: 0.2px;}" +
            "h2, h1 {font-style: italic;}" +
            "h4 {background-color: #DEE3E9; font-family: \"Lucida Console\", \"Courier New\"; padding: 8px;}" +
            "h5 {font-family: Verdana, sans-serif;}" +
            "body {background-color: #F1F1F1;}" +
            ".code {font-family: \"Lucida Console\", \"Courier New\", monospace;}" +
            ".func_block {background-color: #FFFFFF;} </style>";

    private final Datapack datapack;

    private final TypeManager typeManager;

    private final Options options;

    public Printer(Datapack datapack, Options options, TypeManager typeManager) {
        this.datapack = datapack;
        this.typeManager = typeManager;
        this.options = options;
    }

    /**
     * Attempts to print the given Datapack. Does not indicate whether it succeeds or not.
     */
    public static void printDatapack(Datapack datapack, Options options, TypeManager typeManager) {
        Printer printer = new Printer(datapack, options, typeManager);
        printer.print();
    }

    private void print() {
        if (!checkPath(options.outputPath, options.canOverwrite))
            return;

        try (FileWriter writer = new FileWriter(options.outputPath)) {
            writer.write(generateHtml());
            Logger.write("Wrote to " + options.outputPath);
        } catch (Exception e) {
            Logger.write("Failed Print: " + e);
        }
    }

    private boolean checkPath(String path, boolean canOverwrite) {
        File file = new File(path);
        if (!file.exists())
            return true;

        if (!canOverwrite) {
            if (!file.isDirectory()) {
                Logger.write("File already exists! Use the flag [overwrite=<true|false>] to specify whether overwriting is permitted");
            } else {
                Logger.write("Can not overwrite a directory");
            }
            return false;
        }
        return true;
    }

    private String generateHtml() {
        String header =
            "<!DOCTYPE html>" +
            "<html>" +
            "<head>" +
                "<title>" + datapack.name() + "</title>" +
                STYLE_BLOCK +
            "</head>" +
            "<body>";

        String footer =
            h5("Automatically generated by MCFDoc on " + currentDate()) +
            "</body></html>";

        return header + generateInfo() +  generateBody() + footer;
    }

    private String generateBody() {
        StringBuilder body = new StringBuilder();

        for (FunctionGroup group : datapack.groups()) {
            for (Function f : group.functions()) {
                if (!f.isHidden() || options.showHidden) {
                    body.append(generateFunctionBodyHtml(f));
                }
            }
        }
        return body.toString();
    }

    private String currentDate() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yy");
        return df.format(new Date());
    }

    private String h5(String content) {
        return "<h5>" + content + "</h5>";
    }

    private String h4(String content) {
        return "<h4>" + content + "</h4>";
    }

    private String h2(String content) {
        return "<h2>" + content + "</h2>";
    }

    private String h1(String content) {
        return "<h1>" + content + "</h1>";
    }

    private String h3(String content) {
        return "<h3>" + content + "</h3>";
    }

    private String div(String clazz, String content) {
        return "<div class=\"" + clazz + "\">" +
                content + "</div>";
    }

    private String fontColour(String colour, String content) {
        return "<font color=\"#" + colour + "\">" + content + "</font>";
    }

    private String p(String content) {
        return "<p>" + content + "</p>";
    }

    private String sanitise(String content) {
        return new HtmlSanitiser(content, options.html).sanitise();
    }

    /*
    Generates a header listing some information (name, description, author) about the Datapack
     */
    private String generateInfo() {
        StringBuilder sb = new StringBuilder(h1(sanitise(datapack.name())));
        if (datapack.hasDescription()) {
            sb.append(h3("Description"))
              .append(p(sanitise(datapack.description())));
        }
        if (datapack.hasCredits()) {
            sb.append(h3("Credits"))
              .append(p(sanitise(datapack.author())));
        }
        if (datapack.hasVersion()) {
            sb.append(h3("Version"))
                .append(p(sanitise(datapack.version())));
        }
        if (!typeManager.getCustomTypes().isEmpty()) {
            sb.append(h2("Type summary"));
            for (CustomType type : typeManager.getCustomTypes()) {
                sb.append(generateTypeBodyHtml(type));
            }
        }
        sb.append(h2("Function summary"));
        return sb.toString();
    }

    private String generateTypeBodyHtml(CustomType type) {
        return div("func_block", h4(sanitise(type.name())) +
                div("code",
                        p(sanitise(type.description()))
                )
        );
    }

    private String generateFunctionName(Function function) {
        // Do I need to sanitise function names?
        // Probably not as valid mcfunctions can not contain <s or >s.
        // However, names are not checked to be valid by MCFDoc, so I do currently.
        // Could add a feature to note invalid function names?
        String name = sanitise(function.name());
        if (function.isDeprecated())
            name += fontColour("BB1111", " (Deprecated) ");
        if (function.isHidden())
            name += fontColour("1111BB", " (Hidden)");
        return h4(name);
    }

    /*
    Creates the div containing all the information about the Function given
     */
    private String generateFunctionBodyHtml(Function function) {
        return div("func_block", generateFunctionName(function) +
                   div("code",
                        p(generateFunctionString(function))) +
                   p(sanitise(function.description())) +
                   generateParameterBlock(function) +
                   generateTagBlock(function)
        );
    }

    /*
    Generates a block of text listing all the
     */
    private String generateTagBlock(Function function) {
        Collection<List<Tag>> tagTypes = function.tags().getTags();
        if (tagTypes.isEmpty())
            return "";

        StringBuilder sb = new StringBuilder();
        for (List<Tag> tagList : tagTypes) {
            /* Tag title */
            sb.append(h5(sanitise(tagList.getFirst().getName())));
            /* Tag body */
            for (Tag tag : tagList) {
                if (tag.getBody().isEmpty()) {
                    sb.append(p("—")); // Add a gap to make it format more nicely
                } else {
                    sb.append(p(sanitise(tag.getBody())));
                }
            }
        }
        return sb.toString();
    }

    private String generateParameterBlock(Function function) {
        if (function.parameters().isEmpty())
            return "";

        String title = h5("Parameters");
        StringBuilder sb = new StringBuilder("<p>");
        for (Parameter param : function.parameters()) {
            sb.append(sanitise(param.name()));
            if (!param.info().isEmpty()) {
                sb.append(" - ").append(sanitise(param.info()));
            }
            sb.append("<br>");
        }
        sb.append("</p>");
        return title + sb;
    }

    private String generateFunctionString(Function function) {
        StringBuilder sb = new StringBuilder(sanitise(function.name()) + "(");
        int i = 0;
        for (Parameter param : function.parameters()) {
            ++i;
            if (options.prefixTypesInOutput) {
                sb.append(param.type().getColouredName()).append(" ").append(sanitise(param.name()));
            } else {
                sb.append(sanitise(param.name())).append(": ").append(param.type().getColouredName());
            }
            if (i != function.parameters().size()) {
                sb.append(", ");
            }
        }
        sb.append(")");
        return sb.toString();
    }

}
